# Generated by Django 3.2.15 on 2022-08-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('atr_1', models.CharField(max_length=30)),
                ('atr_2', models.CharField(max_length=30)),
                ('atr_3', models.CharField(max_length=30)),
                ('atr_4', models.CharField(max_length=30)),
                ('atr_5', models.CharField(max_length=30)),
                ('atr_6', models.CharField(max_length=30)),
                ('atr_7', models.CharField(max_length=30)),
                ('atr_8', models.CharField(max_length=30)),
                ('atr_9', models.CharField(max_length=30)),
            ],
        ),
    ]
